name: Deploy to Digital Ocean

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            cd onlineide_frontend
            git pull
            npm ci
            npm run build
            pm2 restart vite-preview
